### ISSUE TITLE
UCPv0.2: change the identity document timestamp

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin-python-api#14]
The identity document (self-certification) is changing. The timestamp field previously was a realtime ("real life" timestamp) and will now be a blocktime.

Previously we had:

    UID:IDENTIFIER
    META:TS:TIMESTAMP
    SIGNATURE

Now we have:

    UID:IDENTIFIER
    META:TS:BLOCK_NUMBER-BLOCK_HASH
    SIGNATURE

This change has impact on:

* identity document
* certification document (because the identity to be signed has a new format)
* revokation document (idem)

**Comment by Insoleet** [comment]
I suppose that it changes also the inline format of identity documents to the following ?
```
PUBKEY:UID:BLOCK_NUMBER-BLOCK_HASH:SIGNATURE
```

**Comment by c-geek** [comment]
Duplicate of #17
