### ISSUE TITLE
Identity document changed

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin-python-api#17]
Original changes:

* https://github.com/ucoin-io/ucoin/issues/266 (blocktime reference instead of arbitrary time)
* https://github.com/ucoin-io/ucoin/issues/262 (SHA1 -> SHA256)
* https://github.com/ucoin-io/ucoin/issues/327 (Version: 2)

-----

There is now an Identity document, previously known as "self-certification". It has a new structure like the following example taken from protocol:

    Version: 2
    Type: Identity
    Currency: beta_brousouf
    Issuer: HgTTJLAQ5sqfknMq7yLPZbehtuLSsKj9CxWN7k8QvYJd
    UniqueID: lolcat
    Timestamp: 32-DB30D958EE5CB75186972286ED3F4686B8A1C2CD
    J3G9oM5AKYZNLAB5Wx499w61NuUoS57JVccTShUbGpCMjCqj9yXXqNq7dyZpDWA6BxipsiaMZhujMeBfCznzyci

The main changes are:

* A full document with fields, notably headers Version, Type and Issuer
* Field Version now equals `2`
* Timestamp is now a blocktime reference (or BLOCK_UID), so an identity cannot be created with an arbitrary future time

**Comment by c-geek** [comment]
It also has an impact on Block document where `Identities` field now has format:

    PUBLIC_KEY:SIGNATURE:I_BLOCK_UID:USER_ID

Where:

* `I_BLOCK_UID` is the Identity `Timestamp` field value
* `USER_ID` is the Identity `UniqueID` field value
* `SIGNATURE` is the Identity `SIGNATURE` field value
* `PUBLIC_KEY` is the Identity `Issuer` field value

**Comment by Insoleet** [comment]
Done !
