### ISSUE TITLE
Revocation document change

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin-python-api#21]
Original change in https://github.com/ucoin-io/ucoin/issues/196

-----

Protocol rule: https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md#revocation

The Revocation document has changed, and also has an impact on Block document which now has a `Revoked` field with inline revocations in it:

    PUBLIC_KEY:SIGNATURE

**Comment by Insoleet** [comment]
Done!
