### ISSUE TITLE
Standardized UCP documents

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/ucoin-python-api#22]
Original change in https://github.com/ucoin-io/ucoin/issues/344

------

All is said in the original issue. So we now have:

* Identity
* Certification
* Revocation
* Membership
* Block
* Transaction
* Peer

With a shared header:

    Version: VERSION
    Type: DOCTYPE
    Currency: CURRENCY

Also, each document either has a `Issuer` or `Issuers` field.

**Comment by Insoleet** [comment]
Done !
